package it.polimi.ingsw.model.ship.components;

public enum ComponentType {
    CABIN_START, CABIN, ENGINE_SINGLE, ENGINE_DOUBLE, CANNON_SINGLE, CANNON_DOUBLE, SHIELD,
    BATTERY, CARGO_HOLD, CARGO_HOLD_SPECIAL, LIFE_SUPPORT_BROWN, LIFE_SUPPORT_PURPLE, STRUCTURAL;
}
