#!/usr/bin/env python3
"""Generates detailed UML from the source tree, one diagram per package.

The requirement allows the detailed diagrams to be tool-generated. Nothing off the shelf
was available offline that reads modern Java records and sealed interfaces, both of which
this codebase leans on heavily and neither of which is optional detail here — a sealed
interface is how the protocol says "these and no others".

So the tool ships with the repository. It reads declarations rather than compiling, which
is enough for a class diagram and keeps it to one file with no dependencies.

Usage:
    python3 tools/uml/generate-detailed.py src/main/java docs/uml/detailed
"""

import pathlib
import re
import sys
from collections import defaultdict

# A type declaration: kind, name, and whatever it extends, implements or permits.
DECLARATION = re.compile(
    r"^\s*(?:public\s+|final\s+|sealed\s+|non-sealed\s+|abstract\s+|static\s+)*"
    r"(class|interface|enum|record)\s+(\w+)"
    r"(?:\s*<[^>]*>)?"           # type parameters
    r"(?:\s*\([^)]*\))?"         # a record's components
    r"([^{]*)",                  # extends / implements / permits
    re.MULTILINE,
)

# A method somebody outside the package could call. Interface methods carry no modifier, so
# the visibility is optional — which means the pattern also matches `if (`, `throw new ...(`
# and every other line that happens to be two words and a bracket. NOT_A_METHOD is what keeps
# those out; without it the diagrams filled up with methods called "if".
#
# `private` has to be turned away by name. Left to itself the optional visibility skips over it
# and the return type swallows the rest, so `private <T> List<T> askTheDesk(...)` was drawn as
# a public `+askTheDesk() : private <T> List<T>` — the word left in the type being the tell.
PUBLIC_METHOD = re.compile(
    r"^\s{4}(?!private\b)(?:(?:public|protected)\s+)?"
    r"(?:static\s+|final\s+|synchronized\s+|abstract\s+|default\s+)*"
    r"([A-Za-z_$][\w.<>\[\],?]*(?:\s*<[^;{]*?>)?)\s+([a-z_$]\w*)\s*\(",
    re.MULTILINE,
)

NOT_A_METHOD = {
    "if", "for", "while", "switch", "catch", "return", "throw", "new", "super", "this",
    "synchronized", "assert", "else", "do", "try", "yield", "case", "record", "class",
    "interface", "enum",
}

# A field the class keeps.
FIELD = re.compile(
    r"^\s{4}(?:private|protected|public)\s+(?:static\s+|final\s+)*"
    r"([\w.<>\[\],\s?]+?)\s+(\w+)\s*[;=]",
    re.MULTILINE,
)

SKIP = {"package-info.java", "module-info.java"}


def strip_comments(text):
    """Removes block and line comments, so a word in prose is never read as code."""
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    return re.sub(r"//[^\n]*", "", text)


def shorten(type_name):
    """Drops package qualifiers, which make a diagram unreadable without adding anything."""
    cleaned = " ".join(type_name.split())
    return re.sub(r"\b[a-z][\w]*(?:\.[a-z][\w]*)*\.", "", cleaned)


def read(path):
    """Reads one file into a description of the types it declares."""
    body = strip_comments(path.read_text(encoding="utf-8"))
    types = []
    for kind, name, tail in DECLARATION.findall(body):
        extends = re.search(r"\bextends\s+([\w.<>,\s]+?)(?:\bimplements\b|\bpermits\b|$)", tail)
        implements = re.search(r"\bimplements\s+([\w.<>,\s]+?)(?:\bpermits\b|$)", tail)
        types.append({
            "kind": kind,
            "name": name,
            "extends": [shorten(one) for one in (extends.group(1).split(",") if extends else [])],
            "implements": [shorten(one) for one in
                           (implements.group(1).split(",") if implements else [])],
        })
    if not types:
        return []
    # Members are attributed to the outermost type: nested ones are usually the variants of
    # a sealed interface, and listing their members separately buries the shape.
    seen = set()
    methods = []
    for returns, name in PUBLIC_METHOD.findall(body):
        if name in NOT_A_METHOD or returns.split()[-1] in NOT_A_METHOD:
            continue
        if name in seen:
            continue
        seen.add(name)
        methods.append((shorten(returns), name))
    types[0]["methods"] = methods[:14]
    types[0]["fields"] = [(shorten(kind), name)
                          for kind, name in FIELD.findall(body)][:12]
    return types


def diagram(package, types):
    """Renders one package as PlantUML."""
    lines = [
        "@startuml " + package.replace(".", "_"),
        "' Generated by tools/uml/generate-detailed.py. Do not edit by hand.",
        "!pragma layout smetana",
        "skinparam shadowing false",
        "skinparam classAttributeIconSize 0",
        "title " + package,
        "",
    ]
    declared = {one["name"] for one in types}
    for one in types:
        keyword = {"record": "class", "enum": "enum",
                   "interface": "interface", "class": "class"}[one["kind"]]
        stereotype = " <<record>>" if one["kind"] == "record" else ""
        lines.append(f"{keyword} {one['name']}{stereotype} {{")
        for kind, name in one.get("fields", []):
            lines.append(f"  -{name} : {kind}")
        if one.get("fields") and one.get("methods"):
            lines.append("  --")
        for returns, name in one.get("methods", []):
            lines.append(f"  +{name}() : {returns}")
        lines.append("}")
    lines.append("")
    for one in types:
        for parent in one["extends"]:
            if parent in declared:
                lines.append(f"{parent} <|-- {one['name']}")
        for contract in one["implements"]:
            if contract in declared:
                lines.append(f"{contract} <|.. {one['name']}")
    lines.append("@enduml")
    return "\n".join(lines) + "\n"


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        return 1
    source, output = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    output.mkdir(parents=True, exist_ok=True)

    packages = defaultdict(list)
    for file in sorted(source.rglob("*.java")):
        if file.name in SKIP:
            continue
        package = str(file.parent.relative_to(source)).replace("/", ".")
        packages[package].extend(read(file))

    written = 0
    for package, types in sorted(packages.items()):
        if not types:
            continue
        name = package.replace("it.polimi.ingsw.", "").replace(".", "-")
        (output / f"{name}.puml").write_text(diagram(package, types), encoding="utf-8")
        written += 1
    print(f"{written} diagrams written to {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
